// POC-REACT/blogproject/src/components/rightComp.jsx
import React from 'react';
import RecentPostComp from './recentPostComp';
import AdvertisementComp from './advertisementComp';

function RightComp({recentPosts}) {
  // console.log(recentPosts)
  return (
    <div className="right">
      <div className="recent-post">
        <h3>Recent post</h3>
        <RecentPostComp recentPosts={recentPosts}/>
      </div>
      <div className="advertisement">
        <AdvertisementComp />
      </div>
    </div>
  );
}

export default RightComp;

// POC-VUE/blogproject/src/components/Landing Page/rightComp/rightComp.vue
<template>
    <div class="right">
      <div class="recent-post">
        <h3>Recent post</h3>
        <RecentPostComp :recentPosts="recentPosts" />
      </div>
      <div class="advertisement">
        <AdvertisementComp />
      </div>
    </div>
  </template>
  
  <script>
  import RecentPostComp from '../recentPost/recentPost.vue'; 
  import AdvertisementComp from '../advertisement/advertisement.vue';
  
  export default {
    name: 'RightComp',
    components: {
      RecentPostComp,
      AdvertisementComp
    },
    props: {
      recentPosts: Array 
    }
  };
  </script>
  
  <style src="./rightComp.css" scoped>
</style>
