// POC-REACT/blogproject/src/components/header.jsx
import "../style/header-footer.css"
import "../style/mobile.css"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faMagnifyingGlass, faBars } from '@fortawesome/free-solid-svg-icons'

import React ,{ useState }from "react"
import { HambergerComp } from "./hambergerComp"
import { Link } from "react-router-dom"
function Header(){
    const [isvisible,setisvisible] = useState(false);


    const hambegerclose =()=>{
        setisvisible(false);

    }
    return <div className="main-container">
    <header className="header">
        <Link to="/"><img id="logo" src="../images/headerlogo.png" alt="" /></Link>
        <div>
            <button className="red-btn"><b>Subscribe!</b></button>
            <button className="search-landing">
            <FontAwesaomeIcon icon={faMagnifyingGlass} size="2xl" style={{color: "#000000",}} />
            </button>
            <button onClick={()=>setisvisible(true)} className="hamburger">
            <FontAwesomeIcon  icon={faBars} size="2xl" style={{color: "#000000",}} />
            </button>
        </div>
        
    </header>
        {isvisible && <HambergerComp isOpen={{isvisible}} handleClose={hambegerclose} />}
        
    </div>
}
export {Header}

// POC-VUE/blogproject/src/components/Header/header.vue
<template>
    <div class="main-container">
      <header class="header">
        <router-link to="/"><img id="logo" src="../../assets/images/headerlogo.png" alt="" /></router-link>
        <div>
          <button class="red-btn"><b>Subscribe!</b></button>
          <button class="search-landing">
            <font-awesome-icon icon="fa-solid fa-search" size="2xl" style="color: #000000;" />
          </button>
          <button @click="openHamburger" class="hamburger">
            <font-awesome-icon icon="fa-solid fa-bars" size="2xl" style="color: #000000;" />
          </button>
        </div>
      </header>
      <!-- Hamburger Menu -->
      <HamburgerComp :isOpen="isvisible" @handleClose="closeHamburger" />
    </div>
  </template>
  
  <script>
  import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
  import  HamburgerComp  from "../Header/Hamburger/hamburgermenu"
 
  
  export default {
    name:"HeaderComp",
    components: {
      FontAwesomeIcon,
      HamburgerComp
    },
    data() {
      return {
        isvisible: false
      };
    },
    methods: {
      closeHamburger() {
        this.isvisible = false;
      },
      openHamburger() {
        this.isvisible = true;
      },
    }
  };
  </script>
  
  <style scoped>
  @import '../Header/header.css';
  </style>
