// POC-REACTNATIVE/blogproject/components/Header/header.jsx
import React, { useState } from 'react';
import { View, Image, Button, TouchableOpacity, Text  } from 'react-native';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faSearch, faBars } from '@fortawesome/free-solid-svg-icons';
import headerStyles from './headerStyle';
import Hamburger from './HamburgerMenu/hamburger';



// Initialize the library with the required icons
library.add(faSearch, faBars);

export default function Header() {
  const [isHamburgerOpen, setHamburgerOpen] = useState(false);

  const openHamburger = () => {
    setHamburgerOpen(true);
  };

  const closeHamburger = () => {
    setHamburgerOpen(false);
  };
  return (
    <View style={headerStyles.mainContainer}>
      <Image
        source={require('../../assets/images/headerlogo.png')}
        style={headerStyles.logo}
      />

      <View style={headerStyles.Icons}>
        <TouchableOpacity >
          <Text style={headerStyles.text}>SUBSCRIBE</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={() => console.log('Search Button pressed')}>
          <FontAwesomeIcon icon="search" size={20} color="black" />
        </TouchableOpacity>

        <TouchableOpacity onPress={openHamburger}>
          <FontAwesomeIcon icon="bars" size={20} color="black" />
        </TouchableOpacity>

      </View>
      {isHamburgerOpen && (
        <Hamburger isVisible={isHamburgerOpen} onClose={closeHamburger} />
      )}
    </View>
  );
}

// POC-VUE/blogproject/src/components/Header/header.vue
<template>
    <div class="main-container">
      <header class="header">
        <router-link to="/"><img id="logo" src="../../assets/images/headerlogo.png" alt="" /></router-link>
        <div>
          <button class="red-btn"><b>Subscribe!</b></button>
          <button class="search-landing">
            <font-awesome-icon icon="fa-solid fa-search" size="2xl" style="color: #000000;" />
          </button>
          <button @click="openHamburger" class="hamburger">
            <font-awesome-icon icon="fa-solid fa-bars" size="2xl" style="color: #000000;" />
          </button>
        </div>
      </header>
      <!-- Hamburger Menu -->
      <HamburgerComp :isOpen="isvisible" @handleClose="closeHamburger" />
    </div>
  </template>
  
  <script>
  import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
  import  HamburgerComp  from "../Header/Hamburger/hamburgermenu"
 
  
  export default {
    name:"HeaderComp",
    components: {
      FontAwesomeIcon,
      HamburgerComp
    },
    data() {
      return {
        isvisible: false
      };
    },
    methods: {
      closeHamburger() {
        this.isvisible = false;
      },
      openHamburger() {
        this.isvisible = true;
      },
    }
  };
  </script>
  
  <style scoped>
  @import '../Header/header.css';
  </style>
